FROM python:3.8-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libpq-dev gcc

COPY ./requirements.txt /app/

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]